spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
  datasource:
    url: jdbc:mysql://shydb.clqf1jzxe3ds.ap-northeast-2.rds.amazonaws.com:3306/study
    username: admin
    password: sonbae134
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
